feat(component/guidedtour): allow to disable welcome step
Talend/ui pull request #2933
Opened 2020-08-26 10:56 UTC by ncomont

**What is the problem this PR is trying to solve?**

welcom step cannot be disabled

**What is the chosen solution to this problem?**

 allow to disable welcome step by passing `false` to the `disabledWelcomStep` prop

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-08-26 12:07 UTC, gjou-tlnd commented
what's the point of using this component if you are not using welcome step/demo content?

2020-08-27 14:23 UTC, jsomsanith-tlnd commented
Can you explain your need please ?
- it feels weird to jump directly into the demo without welcoming/explaining
- if you need only a guided tour where you set your steps, Like Gwendal said, you have the GuidedTour component

2020-09-08 13:57 UTC, vbocquet approved these changes

2020-09-08 14:05 UTC, romainseb approved these changes

2020-09-08 14:26 UTC, gjou-tlnd commented
@ncomont can you answer to @jsomsanith and me ?

2020-09-08 14:27 UTC, gjou-tlnd requested changes
@ncomont can you answer to @jsomsanith and me ?

2020-09-08 16:04 UTC, gjou-tlnd approved these changes

2020-09-08 16:33 UTC, merged