feat(icons): download.svg, upload.svg
Talend/ui pull request #2969
Opened 2020-09-25 14:19 UTC by mhuet

**What is the problem this PR is trying to solve?**
Update the icon style to be consistent with export and import icons.

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-09-29 14:17 UTC, jmfrancois requested changes
Please pass your icons into SVGO: https://jakearchibald.github.io/svgomg/
<img width="1100" alt="Screenshot 2020-09-29 at 16 17 14" src="https://user-images.githubusercontent.com/19857479/94570579-4825e300-026f-11eb-8f13-cdd4bc54cd71.png">

The size is important

2020-09-30 16:38 UTC, frassinier approved these changes

2020-10-02 13:48 UTC, ncomont approved these changes

2020-10-13 07:49 UTC, jmfrancois approved these changes

2020-10-13 10:02 UTC, merged