chore(forms): upgrading react hook form to v6
Talend/ui pull request #2988
Opened 2020-10-08 14:57 UTC by jlame

**What is the problem this PR is trying to solve?**
some feature available in v6 are needed for schema editor form rewrite

**What is the chosen solution to this problem?**
Here is the guide for migration from v5 to v6 : https://react-hook-form.com/migrate-v5-to-v6/
When migrating my poc to v6, i've encountered some change in how the library manages FieldArray. If you're using this feature, you might need to check that everything's all right.

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-10-09 08:42 UTC, jmfrancois requested changes
please add it to dependencies.json file to help team to align and do not have the lbi twice

2020-10-09 09:32 UTC, vbocquet approved these changes

2020-10-12 13:19 UTC, jmfrancois approved these changes
if it s accepted from team to have to upgrade rhf it is ok for me

2020-10-12 13:38 UTC, tlnd-mhuchet approved these changes

2020-10-12 13:39 UTC, gjou-tlnd approved these changes

2020-10-12 13:41 UTC, romainseb approved these changes

2020-10-13 09:31 UTC, merged