feat(TMC-22424/CellTitle): badge in list cell title
Talend/ui pull request #2989
Opened 2020-10-09 11:34 UTC by VolodymyrKovalM

**What is the problem this PR is trying to solve?**
https://jira.talendforge.org/browse/TMC-22424
![image](https://user-images.githubusercontent.com/20522845/95578340-6abcb680-0a3c-11eb-99db-f4013c73654a.png)

**What is the chosen solution to this problem?**
Implement possibility to have badge between cell title icon and cell title selector

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

2020-11-13 10:21 UTC, jmfrancois approved these changes

2020-11-20 14:17 UTC, jlame approved these changes

2020-12-23 16:38 UTC, jmfrancois requested changes

2020-12-23 16:38 UTC, jmfrancois commented on output/components.eslint.txt
> +  909:33  error  'icons' is not defined                           no-undef
please fix

2021-02-05 11:30 UTC, closed without merging