feat(faceted-search): Add pattern operators
Talend/ui pull request #3000
Opened 2020-10-14 13:15 UTC by gjou-tlnd

**What is the problem this PR is trying to solve?**

Suuport of complies/wordComplies TQL operators is missing

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-10-16 13:40 UTC, vbocquet requested changes
Just add a comment about two tests, after that it seems good for me

2020-10-16 13:40 UTC, vbocquet commented on packages/faceted-search/src/queryClient/tql.js
> +	[operatorNames.complies]: query.complies,
Can you add test for `complies` and `wordComplies` in `/src/queryClient/tql.test.js`

2020-10-20 16:26 UTC, frassinier approved these changes

2020-10-21 07:05 UTC, vbocquet approved these changes

2020-10-21 07:22 UTC, merged