fix(ListView): add class to set display: flex only for item with icon
Talend/ui pull request #3073
Opened 2020-11-16 12:10 UTC by akaseka

**What is the problem this PR is trying to solve?**
listView styles issue
![image](https://user-images.githubusercontent.com/54246061/99251061-5dea6a00-2815-11eb-948c-022c4c3f7c84.png)

**What is the chosen solution to this problem?**
-Add class to set display: flex only for item with an icon

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-11-16 12:19 UTC, inna-i commented on packages/components/src/ListView/Items/Item/Item.component.js
> +			{'with-icon': item.icon},
```suggestion
			{ 'with-icon': item.icon },
```

2020-11-16 12:22 UTC, inna-i approved these changes

2020-11-16 12:24 UTC, mkondzera approved these changes

2020-11-16 12:42 UTC, jmfrancois requested changes
listview in form is broken
<img width="514" alt="Screenshot 2020-11-16 at 13 42 10" src="https://user-images.githubusercontent.com/19857479/99253730-912afa00-2811-11eb-8643-cd9985ee903c.png">

2020-11-17 10:32 UTC, inna-i commented
Looks good: 
![image](https://user-images.githubusercontent.com/11767543/99379170-027db200-28d1-11eb-8a73-3ab696371332.png)

2020-11-17 10:33 UTC, inna-i approved these changes

2020-11-18 08:56 UTC, jsomsanith-tlnd commented on packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
> -
Don’t change a rule globally if the goal is to introduce a specific rule.
The idea is good: remove the star, but only in the ListView
- revert the css removal in FieldTemplate
- add a specific css in ListView style to override the global rule

2020-11-19 09:34 UTC, lmaillet approved these changes

2020-11-19 13:14 UTC, jmfrancois approved these changes

2020-11-19 13:15 UTC, jsomsanith-tlnd commented on packages/forms/src/UIForm/fields/FieldTemplate/FieldTemplate.scss
> -
Drop this suggestion after @frassinier's rework on style

2020-11-19 13:25 UTC, merged