chore(Collapsible): status style
Talend/ui pull request #3096
Opened 2020-11-30 10:34 UTC by jlame

**What is the problem this PR is trying to solve?**
![image (6)](https://user-images.githubusercontent.com/14272767/100599205-00b7e380-3300-11eb-8679-10be06ff65b2.png)

should look like this : 

![image-1](https://user-images.githubusercontent.com/14272767/100599229-09a8b500-3300-11eb-972c-47721904f07d.png)

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2020-12-01 09:51 UTC, jmfrancois requested changes

2020-12-01 09:51 UTC, jmfrancois commented on packages/components/src/CollapsiblePanel/CollapsiblePanel.stories.js
> +				header={[{ label: 'Controlled expanded panel with success status' }]}
id of panels are equals

2020-12-04 16:03 UTC, jmfrancois approved these changes

2020-12-07 08:52 UTC, jsomsanith-tlnd approved these changes

2020-12-07 09:37 UTC, merged