feat(ActionDropdown): applying transformation on icon
Talend/ui pull request #3219
Opened 2021-02-19 08:50 UTC by VolodymyrKovalM

**What is the problem this PR is trying to solve?**
Allow applying transformation on icon in ActionDropdown

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-02-22 08:51 UTC, jmfrancois requested changes

2021-02-22 08:51 UTC, jmfrancois commented on packages/components/src/Actions/ActionDropdown/ActionDropdown.snapshot.test.js
> +		expect(wrapper.html()).toMatchSnapshot();
PLease look for the svg.theme-rotate-90 element to validate the behavior. Not a complete snapshots for that

2021-02-22 13:45 UTC, jmfrancois approved these changes

2021-02-23 03:31 UTC, yyanwang approved these changes

2021-02-23 07:26 UTC, merged