chore(components): Allow custom triggers for OverlayTrigger
Talend/ui pull request #3335
Opened 2021-06-16 14:25 UTC by tlnd-mhuchet

**What is the problem this PR is trying to solve?**
Our `OverlayTrigger` component is a wrapper of the bootstrap one.
If we want to use ours instead of the bootstrap one, it needs to allow the same kind of usage.
But it does not allow to choose how to trigger the overlay, it is only by `click`.

**What is the chosen solution to this problem?**
Add a `trigger` props, with `click` as default value, to allow to use another values (i.e. `hover` or `focus`)

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-06-16 15:04 UTC, vbocquet approved these changes
Seems cool, thanks to add this. 
In bonus, maybe a specific story to show other trigger usage will be great (hover for example), and a story with multiple trigger usage

2021-06-16 15:19 UTC, jmfrancois commented
no more stories please let s wait to have the update of storbook with arguments

2021-06-16 15:43 UTC, jmfrancois requested changes
Please update the tests, we have no CI

2021-06-18 08:07 UTC, jmfrancois approved these changes

2021-06-18 08:10 UTC, merged