chore(forms): Coral InlineMessage
Talend/ui pull request #3348
Opened 2021-06-22 11:01 UTC by frassinier

**What is the problem this PR is trying to solve?**
Inline message in forms use bootstrap markup

**What is the chosen solution to this problem?**
Let's use Coral ones for consistency reasons

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-06-22 15:27 UTC, sgangnant approved these changes

2021-06-22 15:40 UTC, jmfrancois requested changes

2021-06-22 15:40 UTC, jmfrancois commented on yarn.lock
> +  version "7.14.6"
make it aligned please

2021-06-22 15:50 UTC, frassinier commented on yarn.lock
> +  version "7.14.6"
Let's dedup 🚀

2021-06-28 10:00 UTC, jmfrancois approved these changes

2021-06-28 10:00 UTC, merged