feat(UIForm): Support custom root tag
Talend/ui pull request #3392
Opened 2021-08-18 14:56 UTC by gjou-tlnd

**What is the problem this PR is trying to solve?**

It's not possible to use an UIform as part of another form as nesting form is not allowed in HTML

**What is the chosen solution to this problem?**

Support custom html tag when rendering the form

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-08-18 15:01 UTC, frassinier approved these changes

2021-08-19 12:41 UTC, jmfrancois commented on packages/forms/src/UIForm/UIForm.component.js
>  				autoComplete={this.props.autoComplete}
you should not pass not valid props to custom element

2021-08-19 12:42 UTC, jmfrancois requested changes
If you use div for example the div tag will have accept-charset, action and auto-complete attribute which are not valid.

2021-08-19 14:20 UTC, gjou-tlnd commented
> If you use div for example the div tag will have accept-charset, action and auto-complete attribute which are not valid.

it's up to the developer to not provide these props when using a div

2021-08-19 14:37 UTC, jmfrancois approved these changes

2021-08-19 14:40 UTC, merged