feat(icon): restart.svg
Talend/ui pull request #3509
Opened 2021-11-03 10:29 UTC by mhuet

**What is the problem this PR is trying to solve?**

Need an icon for restart action

**What is the chosen solution to this problem?**

Icon has been created

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-11-03 10:30 UTC, Benrajalu approved these changes

2021-11-03 13:09 UTC, jmfrancois requested changes
path is not closed
https://github.com/Talend/ui/tree/master/packages/icons#all-path-are-closed

2021-11-04 09:52 UTC, jsomsanith-tlnd approved these changes

2021-11-04 10:16 UTC, jmfrancois approved these changes

2021-11-04 10:17 UTC, merged