package(cmf-react-router)
Talend/ui pull request #3513
Opened 2021-11-08 15:35 UTC by romainseb

**What is the problem this PR is trying to solve?**
Bring a cmf router for react-router v5
**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2021-11-08 15:50 UTC, jsomsanith-tlnd commented on packages/cmf-react-router/README.md
> +This module is like cmf-router but for React router v5 (and more recent) where @talend/cmf-router is tied up with react-router v3.
I think you should write a real doc and not rely on a package that will be removed when everyone migrates to this one

2021-11-08 15:50 UTC, jsomsanith-tlnd commented on packages/cmf-react-router/README.md
> +	routerFunctions: {},
`routerFunctions ` are not supported anymore here

2021-11-08 15:58 UTC, romainseb commented on .changeset/ci-dependencies.md
> +'@talend/cmf-react-router': patch
It's some configuration stuff here no ? 🙄

2021-11-16 07:59 UTC, jmfrancois requested changes
After discussion we are agree to switch to a major on @talend/react-cmf-router
We will try to bring settings on it to let teams has the time to plan the migration outside the settings.

2021-12-20 09:07 UTC, closed without merging