fix(TDOPS-963/Typeahead): wrong positioning on first opening
Talend/ui pull request #3836
Opened 2022-04-05 07:54 UTC by mkondzera

**What is the problem this PR is trying to solve?**
Sometimes Typeahead dropdown is overflowing the page, and some options are not reachable
**What is the chosen solution to this problem?**
enable adaptive option to fix an issue
**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-04-05 12:08 UTC, Benrajalu approved these changes

2022-04-07 08:03 UTC, romainseb approved these changes

2022-04-07 08:40 UTC, jmfrancois requested changes
please add changeset to get your fix release

2022-04-07 09:45 UTC, jmfrancois approved these changes

2022-04-07 11:58 UTC, merged