feat(faceted-search) replace preview switch by new switch component f…
Talend/ui pull request #3846
Opened 2022-04-06 10:04 UTC by AdelineMrtn

…rom design system

**What is the problem this PR is trying to solve?**

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-04-06 13:51 UTC, Kporal commented on packages/faceted-search/.storybook/preview.js
> +import {ThemeProvider} from '@talend/design-system';
```suggestion
import { ThemeProvider } from '@talend/design-system';
```

2022-04-06 15:07 UTC, frassinier commented on packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
> +	</form>
You can use the Form component from the DS too
```suggestion
	<Form>
		<Form.Switch
			label={t('FACETED_SEARCH_QUERY', 'Query')}
			onChange={() => onChange(facetedMode === FACETED_MODE.BASIC ? FACETED_MODE.ADVANCED : FACETED_MODE.BASIC)}
			dataFeature={facetedMode === FACETED_MODE.BASIC ? USAGE_TRACKING_TAGS.ADVANCED : USAGE_TRACKING_TAGS.BASIC}
		/>
	</Form>
```

2022-04-06 15:27 UTC, ncomont requested changes

2022-04-06 15:27 UTC, ncomont commented on packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
> +			dataFeature={facetedMode === FACETED_MODE.BASIC ? USAGE_TRACKING_TAGS.ADVANCED : USAGE_TRACKING_TAGS.BASIC}
shouldn't it be the opposite ?

2022-04-06 15:36 UTC, AdelineMrtn commented on packages/faceted-search/src/components/FacetedToolbar/FacetedToolbar.component.js
> +			dataFeature={facetedMode === FACETED_MODE.BASIC ? USAGE_TRACKING_TAGS.ADVANCED : USAGE_TRACKING_TAGS.BASIC}
what do you mean by that please ?

2022-04-07 11:48 UTC, Nigui approved these changes

2022-04-07 12:44 UTC, merged