fix(datagrid): Translation not extracted in TS files
Talend/ui pull request #4050
Opened 2022-05-30 15:09 UTC by gjou-tlnd

**What is the problem this PR is trying to solve?**

- datagrid locales are not loaded
- tsx files are ignored when exporting locales

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-05-30 15:13 UTC, sgangnant approved these changes

2022-05-30 15:26 UTC, jmfrancois requested changes

2022-05-30 15:26 UTC, jmfrancois commented on yarn.lock
> +typescript@^3.0.0:
please ... could you at least force resolution to avoid

2022-05-31 08:49 UTC, jmfrancois approved these changes
ok but let's use something else like i18next-parser please 
i18next-scanner-typescript is dead

2022-05-31 10:16 UTC, merged