chore(icons): Add changeset when importing from figma
Talend/ui pull request #4068
Opened 2022-06-02 12:24 UTC by gjou-tlnd

**What is the problem this PR is trying to solve?**

Add changeset files when icons are imported from figma

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

Linked to https://jira.talendforge.org/browse/TUX-1173

2022-06-02 23:12 UTC, frassinier approved these changes

2022-06-03 07:10 UTC, jmfrancois requested changes
please add a limit. body size of a commit is limited

2022-06-03 07:10 UTC, jmfrancois commented on .github/workflows/icons.yml
> +          while read STATUS ADDR
Nice idea to parse the git status !
```
while read -r line; 
do 
   echo "$line" ;
done < input.file
```

2022-06-03 07:19 UTC, jmfrancois approved these changes
after discussions we should never have more than 4 icons changes so my request change do not apply

2022-06-03 07:32 UTC, merged