Aghomari/tds 6666
Talend/ui pull request #4211
Opened 2022-07-12 07:33 UTC by abdelillah-tech

**What is the problem this PR is trying to solve?**

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-07-12 07:50 UTC, jmfrancois requested changes

2022-07-12 07:50 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +		this.enableSkip = props.enableSkip;
if the value change later on this property will not be updated

2022-07-12 14:58 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +		this.enableSkip = props.enableSkip;
```suggestion
```

2022-07-12 14:58 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +			const formattedValue = EnumerationForm.parseStringValueToArray(value.value, this.enableSkip);
```suggestion
			const formattedValue = EnumerationForm.parseStringValueToArray(value.value, this.props.enableSkip);
```

2022-07-12 14:58 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +				item.values = EnumerationForm.parseStringValueToArray(value.value, this.enableSkip);
```suggestion
				item.values = EnumerationForm.parseStringValueToArray(value.value, this.props.enableSkip);
```

2022-07-12 14:58 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +						value: EnumerationForm.parseStringValueToArray(value.value, this.enableSkip),
```suggestion
						value: EnumerationForm.parseStringValueToArray(value.value, this.props.enableSkip),
```

2022-07-12 14:58 UTC, jmfrancois commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +						values: EnumerationForm.parseStringValueToArray(value.value, this.enableSkip),
```suggestion
						values: EnumerationForm.parseStringValueToArray(value.value, this.props.enableSkip),
```

2022-07-25 09:35 UTC, Kporal commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +	static parseStringValueToArray(values, enableSkip) {
could you add some test for this please?

2022-07-25 09:35 UTC, Kporal commented on packages/forms/src/UIForm/fields/Enumeration/EnumerationWidget.js
> +		enableSkip: PropTypes.bool,
The name is not clear enough, I suggest a rename, don't know if you can find better?
```suggestion
		skipCommas: PropTypes.bool,
```

2022-07-25 13:26 UTC, Kporal approved these changes

2022-07-25 13:29 UTC, jmfrancois approved these changes

2022-07-25 13:34 UTC, merged