feat(datagrid): Support multi column selection
Talend/ui pull request #4220
Opened 2022-07-18 13:04 UTC by gjou-tlnd

**What is the problem this PR is trying to solve?**

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-07-20 16:07 UTC, Benrajalu commented on packages/datagrid/README.md
> +Ag-grid set the current cell selected by a click. If we navigate with the keyboard, ag-grid sent a new event onCellFocused but the cell isn't selected. AgGrid allows to change this behavior by adding
```suggestion
Ag-grid sets the current cell selected by a click. If we navigate with the keyboard, ag-grid sends a new event onCellFocused but the cell isn't selected. AgGrid allows to change this behavior by adding a method _navigateToNextCell_ on these options. Each time that we move to a next cell, this cell is selected. The current selected rows is highlighted by the class _.ag-row-focus_. This class can be overridden by the class _.ag-row-selected_ if many row are selected.
```

2022-07-20 16:07 UTC, Benrajalu commented on packages/datagrid/src/components/DataGrid/DataGrid.tsx
> +		// BEGIN QUICKFIX: Would be better to use gridRef.current?.api.refreshHeader() but it has a weird flicker
What if you set the display of the grid (through opacity, not display: none) to a timer? You keep a skeleton running above for the duration of that timer. Fade out the skeleton / fade in the grid with refreshHeader?

2022-07-20 16:10 UTC, Benrajalu commented on packages/datagrid/src/components/DataGrid/DataGrid.tsx
> +		// BEGIN QUICKFIX: Would be better to use gridRef.current?.api.refreshHeader() but it has a weird flicker
Discussed IRL, that's not it.

2022-07-21 09:05 UTC, sgangnant commented on packages/datagrid/src/serializers/datasetSerializer.test.ts
> +describe('#getColumnDefs', () => {
Why the hashtag ?

```suggestion
describe('getColumnDefs', () => {
```

2022-07-21 09:06 UTC, sgangnant approved these changes

2022-07-21 10:08 UTC, gjou-tlnd commented on packages/datagrid/src/serializers/datasetSerializer.test.ts
> +describe('#getColumnDefs', () => {
dunno, legacy code

2022-07-21 16:07 UTC, jmfrancois requested changes

2022-07-21 16:07 UTC, jmfrancois commented on packages/datagrid/src/components/DataGrid/DataGrid.tsx
> +import { AgGridReact } from 'ag-grid-react';
lazy load please :pray:

2022-07-21 16:13 UTC, gjou-tlnd commented on packages/datagrid/src/components/DataGrid/DataGrid.tsx
> +import { AgGridReact } from 'ag-grid-react';
I need this import, it's used as a type

2022-07-22 09:48 UTC, jmfrancois approved these changes

2022-07-25 08:32 UTC, merged