fix(Datalist/TDOPS-2632): update data list entry if name is not the same
Talend/ui pull request #4250
Opened 2022-07-26 14:55 UTC by VolodymyrKovalM

**What is the problem this PR is trying to solve?**
The entry in Data list is updated only if value has changed
When the title map is asynchronously loaded depending on value of another Data list, 
the name of entry can be the same as value (when the title map has changed, but the value is still old one, and there is not entry with this value in new title map, by default, for some time, the name will be the same as value)
So, this condition won't be true https://github.com/Talend/ui/blob/master/packages/components/src/Datalist/Datalist.component.js#L150 , as the value won't equal to filter value, and so, it won't update filter value, and previous filter value (from previous title map) will be displayed

https://user-images.githubusercontent.com/20522845/181039400-b735536c-e476-4028-84fb-d09e6d390079.mp4

**What is the chosen solution to this problem?**
Update data list entry is name is not the same

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-07-26 15:17 UTC, jmfrancois requested changes
you need a changeset in the PR

2022-07-27 09:16 UTC, gjou-tlnd requested changes
we had lots of issue on this component, please add a test case

2022-07-27 12:17 UTC, jmfrancois approved these changes
Agree with @gjou-tlnd please add a test case.

2022-07-27 14:49 UTC, gjou-tlnd approved these changes

2022-07-27 14:51 UTC, merged