fix(CDN): react-router 6.4.0 in modules.json
Talend/ui pull request #4342
Opened 2022-09-20 14:58 UTC by lmaillet

**What is the problem this PR is trying to solve?**
Before: https://unpkg.com/react-router@6.3.0/umd/react-router.production.min.js
After: https://unpkg.com/react-router@6.4.0/dist/umd/react-router.production.min.js

**What is the chosen solution to this problem?**
Add the `/dist` folder for react-router >= 6.4.0

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-09-20 15:10 UTC, jmfrancois commented on fork/module-to-cdn/modules.json
> +      ">= 6.0.0 < 6.3.0": {
```suggestion
      ">= 6.0.0 < 6.4.0": {
```

2022-09-20 15:17 UTC, jmfrancois approved these changes

2022-09-20 15:18 UTC, jmfrancois requested changes
https://unpkg.com/browse/react-router-dom@6.4.0/ same here

2022-09-20 15:28 UTC, jmfrancois approved these changes

2022-11-04 09:22 UTC, jmfrancois approved these changes

2022-11-04 11:26 UTC, smouillour approved these changes

2022-11-04 13:20 UTC, merged