fix(TDOPS-3299): design system modal z-index to use tokens convention
Talend/ui pull request #4474
Opened 2022-11-30 10:54 UTC by Gbacc

**What is the problem this PR is trying to solve?**
Tooltips on components inside a modal won't show up

**What is the chosen solution to this problem?**
Design system modal will use design token z-index

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2022-11-30 13:22 UTC, jmfrancois requested changes
demo broken ?
![image](https://user-images.githubusercontent.com/19857479/204807298-7ef351ad-bd0f-449b-a722-9f789d7bf924.png)

2022-11-30 14:31 UTC, Gbacc commented on packages/storybook-docs/src/globalStyles.scss
> +	position: relative;
Real change is here 
The root of the storybook is at the first layer of z-index and relative

2022-12-01 07:27 UTC, romainseb approved these changes

2022-12-08 16:07 UTC, jmfrancois approved these changes

2022-12-08 16:45 UTC, merged