fix(TDOPS-3373/NestedListView): include searchCriteria in component update
Talend/ui pull request #4624
Opened 2023-03-12 12:08 UTC by ybaskaran

**What is the problem this PR is trying to solve?**
When loading a new list to the NestedListView, the searchText remains the same but the items in the list are not filtered

**What is the chosen solution to this problem?**
Include searchCriteria in component update to filter out the items not matching the searchText when loading the new list

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2023-03-14 08:06 UTC, Nigui approved these changes

2023-03-14 14:54 UTC, jmfrancois requested changes

2023-03-16 18:05 UTC, ybaskaran commented on packages/forms/src/UIForm/fields/NestedListView/NestedListView.test.js
> +			const wrapper = shallow(<NestedListViewWidget {...props} />);
added RTL

2023-03-16 18:57 UTC, jmfrancois approved these changes

2023-03-16 18:58 UTC, merged