fix(TDOPS-4043/NestedList): expand the list if any item is checked
Talend/ui pull request #4670
Opened 2023-04-10 16:29 UTC by ybaskaran

**What is the problem this PR is trying to solve?**
No option to show the nested list items in expanded mode

**What is the chosen solution to this problem?**
Add an option to expand the list if any of the item under the nested list is checked

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2023-04-11 07:43 UTC, jmfrancois requested changes

2023-04-11 07:43 UTC, jmfrancois commented on .changeset/long-ants-move.md
> +'@talend/react-forms': patch
this is a feature not a fix

2023-04-11 07:43 UTC, jmfrancois commented on packages/forms/stories/json/fields/core-nestedListView.json
> +          "checked": true
I don't understand the story behind sorry.
The option should be enough.
if option and items.length >0 => expand.
Also checked in uischema do not look like an item data.

2023-04-12 15:51 UTC, jmfrancois approved these changes

2023-04-13 07:11 UTC, romainseb approved these changes

2023-04-13 07:38 UTC, merged