fix(TDOPS-4682): Fix design system form file to integrate on TMC
Talend/ui pull request #4800
Opened 2023-07-13 12:19 UTC by Gbacc

**What is the problem this PR is trying to solve?**
Fix design system form file to integrate on TMC
- `files` prop to be taken into account when changing
- on file clear, trigger `onChange` event

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [x] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2023-07-13 13:11 UTC, jmfrancois requested changes
add test case please

2023-07-18 08:02 UTC, romainseb approved these changes

2023-07-18 08:52 UTC, jmainguytalend approved these changes

2023-07-18 09:42 UTC, jmfrancois approved these changes

2023-07-18 09:43 UTC, merged