fest(TDOPS-5189/icons): Update Qlik svg with the one provided by Qlik
Talend/ui pull request #4911
Opened 2023-09-28 12:54 UTC by smouillour

**What is the problem this PR is trying to solve?**
Update Qlik svg with the one provided by Qlik

**What is the chosen solution to this problem?**

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2023-09-28 13:41 UTC, jmfrancois requested changes
![image](https://github.com/Talend/ui/assets/19857479/64cd5da6-caa8-4726-a0f2-e64b7eb29be1)

2023-09-29 10:35 UTC, smouillour commented
@jmfrancois it's back to normal
![CleanShot 2023-09-29 at 12 34 56](https://github.com/Talend/ui/assets/32456736/2cfb710e-647d-44ed-8a6d-ac88c26fb662)

2023-09-29 11:34 UTC, inna-i approved these changes

2023-09-29 12:03 UTC, jmfrancois approved these changes

2023-09-29 12:03 UTC, jmfrancois commented on packages/icons/src/svg/products/qlik-colored.svg
> +        d="m 12.02985,7.6825299 c 0,2.6068651 -2.0495995,4.7204131 -4.5784999,4.7204131 -2.5287701,0 -4.5787401,-2.113548 -4.5787401,-4.7207744 0,-2.6069164 2.04997,-4.7200212 4.5787401,-4.7200212 2.
I was wondering what is the diff between m and M, look 
![image](https://github.com/Talend/ui/assets/19857479/7492d768-0297-4d08-ab18-72408a7a3672)

2023-09-29 12:12 UTC, merged