fix(TFD-16296): Add ellipsis on collapsible panel
Talend/ui pull request #4926
Opened 2023-10-06 14:59 UTC by tlnd-mhuchet

**What is the problem this PR is trying to solve?**
Collapsible panel does not handle the text overflow for all cases in the header.

For example, when you have a simple header with a label and one action, the whole in a very tiny space, you got a multiline label that exit the panel header.

![CleanShot 2023-10-06 at 16 55 09@2x](https://github.com/Talend/ui/assets/59565911/61c4489d-82b1-4e07-b60d-3b7f548b1198)

https://jira.talendforge.org/browse/TFD-16296

**What is the chosen solution to this problem?**
The goal is to prevent the overflow with a nice ellipsis and the whole text in a tooltip.

![CleanShot 2023-10-06 at 16 57 35@2x](https://github.com/Talend/ui/assets/59565911/dbd2ecd1-3b29-41ce-9b83-6e38b3a9462a)

A story has been added to show the case in storybook.

![CleanShot 2023-10-06 at 16 58 32@2x](https://github.com/Talend/ui/assets/59565911/33b5f98e-2529-4c54-bc92-f7c5d6fdaa5d)

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

2023-10-06 15:03 UTC, jmfrancois requested changes
this make it impossible to read !

2023-10-09 06:22 UTC, itenger-talend approved these changes

2023-10-09 07:04 UTC, aamalric-talend approved these changes
LGTM

2023-10-09 10:05 UTC, jmfrancois approved these changes
it seems there is a tooltip already

2023-10-09 12:10 UTC, merged